### ISSUE TITLE
Setup of the ElkapodHardwareController_software repository

### ISSUE THREAD

**Issue by VisteK528** [HexapodBionik/ElkapodHardwareController_software#2]
# ToDo's
- [x] Create two separate workflow branches for actual Hardware Controller(our STM32F446ZET6 based board) and for Hardware Controller Mockup (my custom STM32L476RG board)
- [x] Generate files for main Hardware Controller and move any code from the older Hardware Controller repo that can be now moved without any or with small modifications.
- [x] Generate files for Hardware Controller mockup with threads for communication (via USB FS), logic and IMU.
